import type { Report, Analytics, AQIPrediction } from '@/types'

// Bangalore-centric demo data
export const DEMO_REPORTS: Report[] = [
  {
    id: 'r001',
    userId: 'u001',
    userDisplayName: 'Priya Sharma',
    isAnonymous: false,
    location: { lat: 12.9716, lng: 77.5946, address: 'MG Road, Bengaluru', ward: 'Shivajinagar', district: 'Bengaluru Urban' },
    pollutionType: 'garbage_fire',
    severity: 'high',
    description: 'Large pile of garbage burning near the bus stop causing thick smoke. Multiple people coughing.',
    imageUrl: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=400',
    status: 'pending',
    upvotes: 23,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 30),
    aiAnalysis: {
      pollutionType: 'garbage_fire',
      confidence: 0.94,
      smokeDetected: true,
      dustDetected: false,
      fireDetected: true,
      possibleSource: 'Municipal solid waste burning',
      estimatedSeverity: 'high',
      healthRisk: 'severe',
      recommendedAction: 'Immediate action required. Contact BBMP sanitation department.',
      estimatedAQI: 285,
      summary: 'Active garbage fire detected with dense smoke. PM2.5 levels likely above 150 μg/m³.',
      analyzedAt: new Date(Date.now() - 1000 * 60 * 29),
    },
  },
  {
    id: 'r002',
    userId: null,
    userDisplayName: null,
    isAnonymous: true,
    location: { lat: 12.9352, lng: 77.6245, address: 'Koramangala 5th Block, Bengaluru', ward: 'Koramangala', district: 'Bengaluru Urban' },
    pollutionType: 'construction_dust',
    severity: 'medium',
    description: 'Metro construction site generating massive dust clouds. No dust suppression measures.',
    status: 'acknowledged',
    upvotes: 14,
    createdAt: new Date(Date.now() - 1000 * 60 * 120),
    updatedAt: new Date(Date.now() - 1000 * 60 * 90),
    aiAnalysis: {
      pollutionType: 'construction_dust',
      confidence: 0.88,
      smokeDetected: false,
      dustDetected: true,
      fireDetected: false,
      possibleSource: 'Metro rail construction activity',
      estimatedSeverity: 'medium',
      healthRisk: 'moderate',
      recommendedAction: 'Require construction site to use water spraying for dust suppression.',
      estimatedAQI: 145,
      summary: 'Significant construction dust detected. Suspended particulate matter elevated.',
      analyzedAt: new Date(Date.now() - 1000 * 60 * 119),
    },
  },
  {
    id: 'r003',
    userId: 'u002',
    userDisplayName: 'Rahul Kumar',
    isAnonymous: false,
    location: { lat: 13.0298, lng: 77.5928, address: 'Hebbal Flyover, Bengaluru', ward: 'Hebbal', district: 'Bengaluru Urban' },
    pollutionType: 'vehicle',
    severity: 'medium',
    description: 'Heavy traffic jam with many old diesel trucks idling. Strong exhaust fumes.',
    status: 'in_progress',
    upvotes: 31,
    createdAt: new Date(Date.now() - 1000 * 60 * 240),
    updatedAt: new Date(Date.now() - 1000 * 60 * 180),
    aiAnalysis: {
      pollutionType: 'vehicle',
      confidence: 0.91,
      smokeDetected: true,
      dustDetected: false,
      fireDetected: false,
      possibleSource: 'Heavy diesel vehicle exhaust',
      estimatedSeverity: 'medium',
      healthRisk: 'moderate',
      recommendedAction: 'Traffic management and vehicle fitness checks recommended.',
      estimatedAQI: 165,
      summary: 'Vehicle pollution from heavy traffic. NO2 and PM2.5 elevated.',
      analyzedAt: new Date(Date.now() - 1000 * 60 * 239),
    },
  },
  {
    id: 'r004',
    userId: 'u003',
    userDisplayName: 'Meera Nair',
    isAnonymous: false,
    location: { lat: 12.9698, lng: 77.7500, address: 'Whitefield Industrial Area, Bengaluru', ward: 'Whitefield', district: 'Bengaluru Urban' },
    pollutionType: 'industrial',
    severity: 'high',
    description: 'Factory chimney releasing dark smoke without filtration. Smell of chemicals.',
    status: 'resolved',
    upvotes: 47,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    resolvedAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
    resolutionNote: 'KSPCB issued notice to factory. Filtration system installed.',
    aiAnalysis: {
      pollutionType: 'industrial',
      confidence: 0.96,
      smokeDetected: true,
      dustDetected: false,
      fireDetected: false,
      possibleSource: 'Industrial chemical plant',
      estimatedSeverity: 'high',
      healthRisk: 'severe',
      recommendedAction: 'Immediate KSPCB intervention required.',
      estimatedAQI: 320,
      summary: 'Industrial pollution with chemical emissions detected. Action taken.',
      analyzedAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    },
  },
  {
    id: 'r005',
    userId: null,
    userDisplayName: null,
    isAnonymous: true,
    location: { lat: 12.8340, lng: 77.6631, address: 'BTM Layout, Bengaluru', ward: 'BTM Layout', district: 'Bengaluru Urban' },
    pollutionType: 'burning_waste',
    severity: 'low',
    description: 'Neighbours burning dry leaves and plastic bags together.',
    status: 'pending',
    upvotes: 8,
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
    updatedAt: new Date(Date.now() - 1000 * 60 * 45),
  },
  {
    id: 'r006',
    userId: 'u004',
    userDisplayName: 'Arun Patel',
    isAnonymous: false,
    location: { lat: 12.9902, lng: 77.5600, address: 'Rajajinagar, Bengaluru', ward: 'Rajajinagar', district: 'Bengaluru Urban' },
    pollutionType: 'smoke',
    severity: 'medium',
    description: 'Heavy smog visible over the area. Cannot see buildings 500m away.',
    status: 'pending',
    upvotes: 19,
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
    updatedAt: new Date(Date.now() - 1000 * 60 * 15),
    aiAnalysis: {
      pollutionType: 'smoke',
      confidence: 0.82,
      smokeDetected: true,
      dustDetected: true,
      fireDetected: false,
      possibleSource: 'Multiple pollution sources combined',
      estimatedSeverity: 'medium',
      healthRisk: 'high',
      recommendedAction: 'Advise citizens to wear masks. Investigate emission sources.',
      estimatedAQI: 195,
      summary: 'Dense smog condition. Mixed particulate matter from multiple sources.',
      analyzedAt: new Date(Date.now() - 1000 * 60 * 14),
    },
  },
]

export const DEMO_ANALYTICS: Analytics = {
  totalReports: 284,
  resolvedReports: 167,
  pendingReports: 117,
  avgResponseTimeHours: 18.4,
  estimatedPeopleAffected: 42800,
  mostPollutedArea: 'Hebbal',
  mostImprovedArea: 'Koramangala',
  topPollutionType: 'vehicle',
  reductionPercent: 23,
  monthlyStats: [
    { month: 'Jan', reports: 32, resolved: 21, avgAQI: 168 },
    { month: 'Feb', reports: 28, resolved: 19, avgAQI: 155 },
    { month: 'Mar', reports: 41, resolved: 27, avgAQI: 172 },
    { month: 'Apr', reports: 38, resolved: 29, avgAQI: 159 },
    { month: 'May', reports: 45, resolved: 31, avgAQI: 181 },
    { month: 'Jun', reports: 52, resolved: 40, avgAQI: 145 },
  ],
}

export function generateDemoAQIPrediction(): AQIPrediction[] {
  const baseAQI = 140
  return Array.from({ length: 24 }, (_, i) => {
    const hour = (new Date().getHours() + i) % 24
    const timeVariation = Math.sin((hour / 24) * Math.PI * 2) * 30
    const predicted = Math.max(50, Math.min(350, baseAQI + timeVariation + (Math.random() - 0.5) * 20))
    return {
      hour,
      timestamp: new Date(Date.now() + i * 3600000),
      predictedAQI: Math.round(predicted),
      confidence: Math.round((0.95 - i * 0.015) * 100) / 100,
      factors: {
        weather: 0.4,
        historical: 0.35,
        current: 0.25,
      },
    }
  })
}
